version: '3.8'

networks:
  dns_network:
    driver: bridge
  mycloud_global_net:
    external: true

services:
  redis_root:
    image: redis:latest
    container_name: redis_root
    networks:
      - dns_network

  ns_root:
    build: ./DNS_Nameserver
    container_name: ns_root
    depends_on:
      - redis_root
    environment:
      - REDIS_HOST=redis_root
      - REDIS_PORT=6379
      - NS_NAME=ROOT_SERVER
      - NS_ROLE=ROOT
      - IP_BIND=0.0.0.0
      - PORT_BIND=53
      - ROTLD_HOSTNAME=ns_rotld
    networks:
      - dns_network

  redis_rotld:
    image: redis:latest
    container_name: redis_rotld
    networks:
      - dns_network

  ns_rotld:
    build: ./DNS_Nameserver
    container_name: ns_rotld
    depends_on:
      - redis_rotld
    environment:
      - REDIS_HOST=redis_rotld
      - REDIS_PORT=6379
      - NS_NAME=ROTLD_SERVER
      - NS_ROLE=ROTLD
      - IP_BIND=0.0.0.0
      - PORT_BIND=53
      - MYCLOUD_HOSTNAME=ns_mycloud
    networks:
      - dns_network

  redis_mycloud:
    image: redis:latest
    container_name: redis_mycloud
    networks:
      - dns_network
      - mycloud_global_net

  mycloud_control_plane:
    build: ./DNS_Nameserver
    container_name: control_plane_dns
    command: [ "python", "-u", "control_plane.py" ]
    depends_on:
      - redis_mycloud
    environment:
      - REDIS_HOST=redis_mycloud
    networks:
      - dns_network

  ns_mycloud:
    build: ./DNS_Nameserver
    container_name: ns_mycloud
    depends_on:
      - redis_mycloud
    environment:
      - REDIS_HOST=redis_mycloud
      - REDIS_PORT=6379
      - NS_NAME=MYCLOUD_AUTH
      - NS_ROLE=MYCLOUD
      - IP_BIND=0.0.0.0
      - PORT_BIND=53
    networks:
      - dns_network

  redis_resolver:
    image: redis:latest
    container_name: redis_resolver
    networks:
      - dns_network

  resolver_app:
    build: ./DNS_Resolver
    container_name: dns_resolver_NO_1
    depends_on:
      - ns_root
      - redis_resolver
    environment:
      - RESOLVER_NAME=DNS_Resolver_N1
      - IP_BIND=0.0.0.0
      - PORT_BIND=5333
      - ROOT_HOSTNAME=ns_root
      - NS_TARGET_PORT=53
      - REDIS_HOST=redis_resolver
      - REDIS_PORT=6379
      - DNS_FLOOD_WINDOW=1
      - DNS_FLOOD_MAX_REQS=80
      - DNS_BAN_TIMEOUT=80
      - NXDOMAIN_CACHE_TTL=10
    ports:
      - "5333:5333/udp"
    networks:
      - dns_network

  rotld_api:
      build: ./MyCloud_Manager
      container_name: rotld_api
      command: [ "python", "-u", "rotld_api.py" ]
      ports:
        - "8080:8080"
      environment:
        - ROTLD_REDIS_HOST=redis_rotld
        - ROTLD_PORT=8080
      depends_on:
        - redis_rotld
      networks:
        - dns_network

  mycloud_api:
      build: ./MyCloud_Manager
      container_name: mycloud_api
      command: [ "python", "-u", "myCloud_api.py" ]
      ports:
        - "5050:5000"
      environment:
        - MYCLOUD_REDIS_HOST=redis_mycloud
        - API_PORT=5000
        - API_KEY=micunealta-secreta
        - ROTLD_API_URL=http://rotld_api:8080
      depends_on:
        - redis_mycloud
        - rotld_api
      networks:
        - dns_network

  mycloud_frontend:
        build: ./MyCloud_Manager/mycloudAPI_frontend
        ports:
          - "9000:9000"
        environment:
          - MYCLOUD_API_HOST=mycloud_api
          - MYCLOUD_API_PORT=5000
        depends_on:
          - mycloud_api
        networks:
          - mycloud_global_net
          - dns_network

  rotld_frontend:
    build: ./MyCloud_Manager/rotldAPI_frontend
    ports:
      - "9001:9001"
    environment:
      - ROTLD_API_HOST=rotld_api
      - ROTLD_API_PORT=8080
    depends_on:
      - rotld_api
    networks:
      - dns_network