services:
  edu_site:
    build: .
    container_name: origin_edu_server
    environment:
      - PORT=80
    networks:
      mycloud_global_net:
        ipv4_address: 172.20.0.12
    ports:
      - "8081:80"

networks:
  mycloud_global_net:
    external: true