version: '3.8'

services:
  redis:
    image: redis:alpine
    networks:
      - ddos_net

  pop_lb:
    build: .
    command: python main.py
    ports:
      - "8085-8090:80"
    environment:
      - POP_PORT=80
      - REDIS_HOST=redis
      - GLOBAL_DNS_REDIS=redis_mycloud #din containerul DNS , link-uit prin reteaua Docker
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    networks:
      - ddos_net
      - mycloud_global_net

  waf_node:
    build: .
    command: python waf.py 8000
    restart: always
    #restart: "no"
    environment:
      - REDIS_HOST=redis
      - WAF_FLOOD_WINDOW=1      #parametrii pentru DDoS Flood: Fereastra de timp,
      - WAF_FLOOD_MAX_REQS=50   #Nr max de cereri admise,
      - WAF_BAN_TIMEOUT=60      #Ban Time
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    networks:
      - ddos_net
      - mycloud_global_net


networks:
  ddos_net:
    driver: bridge
  mycloud_global_net:
    external: true